automation: check that exe is an archive
it happened that .ext has been downloaded but content was html
due to sourceforge outage.
Added a test on the sources to ensure an archive has been downloaded.

Fixes errors like:
ERROR: /usr/share/py2exe-py2.7/py2exe-0.6.9.win32-py2.7.exe
Can not open the file as archive

$ cat /usr/share/py2exe-py2.7/py2exe-0.6.9.win32-py2.7.exe
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>

Change-Id: I6a5f8332c27d4ae11fea8511b8f48fdb75c1e75d
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>